name: edge-gateway-link
on:
  push:
    branches:
      - main
    paths:
      - 'packages/edge-gateway-link/**'
      - '.github/workflows/edge-gateway-link.yml'
      - 'pnpm-lock.yaml'
  pull_request:
    paths:
      - 'packages/edge-gateway-link/**'
      - '.github/workflows/edge-gateway-link.yml'
      - 'pnpm-lock.yaml'
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm test:w3link-edge-gateway
  deploy-staging:
    name: Deploy Staging
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
      - run: pnpm install
      - name: Publish app
        uses: cloudflare/wrangler-action@v3
        env:
          ENV: 'staging' # inform the build process what the env is
          SENTRY_TOKEN: ${{secrets.SENTRY_TOKEN}}
          SENTRY_UPLOAD: ${{ secrets.SENTRY_UPLOAD }}
        with:
          apiToken: ${{secrets.CF_TOKEN }}
          workingDirectory: 'packages/edge-gateway-link'
          environment: 'staging'
  changelog:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      paths_released: ${{ steps.tag-release.outputs.paths_released }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: tag-release
        with:
          path: packages/edge-gateway-link
          token: ${{ secrets.GITHUB_TOKEN }}
          include-component-in-tag: true
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && contains(fromJson(needs.changelog.outputs.paths_released), 'packages/edge-gateway-link')
    name: Release
    runs-on: ubuntu-latest
    needs:
      - test
      - changelog
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        env:
          ENV: 'production' # inform the build process what the env is
          SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}
          SENTRY_UPLOAD: ${{ secrets.SENTRY_UPLOAD }}
        with:
          apiToken: ${{ secrets.CF_TOKEN }}
          workingDirectory: 'packages/edge-gateway-link'
          environment: 'production'
